name: CI/CD with Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_ami_id: ${{ vars.AWS_AMI_ID }}
      TF_VAR_key_name: ${{ vars.AWS_KEY_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Get EC2 public IP
        working-directory: terraform
        run: echo "EC2_PUBLIC_IP=$(terraform output -raw instance_public_ip)" >> "$GITHUB_ENV"

      - name: Show EC2 public IP
        run: echo "EC2 public IP is $EC2_PUBLIC_IP"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 659364970665.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t infra-deploy-aws-app ./nodeapp

      - name: Tag Docker image
        run: docker tag infra-deploy-aws-app:latest 659364970665.dkr.ecr.ap-south-1.amazonaws.com/infra-deploy-aws-app:latest

      - name: Push Docker image to ECR
        run: docker push 659364970665.dkr.ecr.ap-south-1.amazonaws.com/infra-deploy-aws-app:latest

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Login to ECR on EC2
        run: |
          aws ecr get-login-password --region ap-south-1 | ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@$EC2_PUBLIC_IP "sudo docker login --username AWS --password-stdin 659364970665.dkr.ecr.ap-south-1.amazonaws.com"

      - name: Deploy application to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ubuntu@$EC2_PUBLIC_IP "
            sudo docker pull 659364970665.dkr.ecr.ap-south-1.amazonaws.com/infra-deploy-aws-app:latest &&
            sudo docker stop infra-deploy-aws-app || true &&
            sudo docker rm infra-deploy-aws-app || true &&
            sudo docker run -d --name infra-deploy-aws-app -p 80:8080 659364970665.dkr.ecr.ap-south-1.amazonaws.com/infra-deploy-aws-app:latest
          "

      - name: Verify container
        run: |
          sudo docker run -d --restart unless-stopped --name infra-deploy-aws-app -p 80:8080 659364970665.dkr.ecr.ap-south-1.amazonaws.com/infra-deploy-aws-app:latest